export default [
  {
    label: "No Poverty",
    value: "1",
    color: "#e6253b",
    imageLink: "/sdg-images/1.png",
  },
  {
    label: "Zero Hunger",
    value: "2",
    color: "#dda63a",
    imageLink: "/sdg-images/2.png",
  },
  {
    label: "Good Health and Well-Being",
    value: "3",
    color: "#4d9e37",
    imageLink: "/sdg-images/3.png",
  },
  {
    label: "Quality Education",
    value: "4",
    color: "#c41b2f",
    imageLink: "/sdg-images/4.png",
  },
  {
    label: "Gender Equality",
    value: "5",
    color: "#ff3b21",
    imageLink: "/sdg-images/5.png",
  },
  {
    label: "Clean Water and Sanitation",
    value: "6",
    color: "#25bde3",
    imageLink: "/sdg-images/6.png",
  },
  {
    label: "Affordable and Clean Energy",
    value: "7",
    color: "#fcc207",
    imageLink: "/sdg-images/7.png",
  },
  {
    label: "Decent Work and Economic Growth",
    value: "8",
    color: "#a31942",
    imageLink: "/sdg-images/8.png",
  },
  {
    label: "Industry, Innovation and Infrastructure",
    value: "9",
    color: "#fc6a27",
    imageLink: "/sdg-images/9.png",
  },
  {
    label: "Reduced Inequalities",
    value: "10",
    color: "#de1166",
    imageLink: "/sdg-images/10.png",
  },
  {
    label: "Sustainable Cities and Communities",
    value: "11",
    color: "#fc9e25",
    imageLink: "/sdg-images/11.png",
  },
  {
    label: "Responsible Consumption and Production",
    value: "12",
    color: "#c08b2e",
    imageLink: "/sdg-images/12.png",
  },
  {
    label: "Climate Action",
    value: "13",
    color: "#407d45",
    imageLink: "/sdg-images/13.png",
  },
  {
    label: "Life Below Water",
    value: "14",
    color: "#0996d9",
    imageLink: "/sdg-images/14.png",
  },
  {
    label: "Life On Land",
    value: "15",
    color: "#57bf2b",
    imageLink: "/sdg-images/15.png",
  },
  {
    label: "Peace, Justice and Strong Institutions",
    value: "16",
    color: "#00699e",
    imageLink: "/sdg-images/16.png",
  },
  {
    label: "Partnerships for the Goals",
    value: "17",
    color: "#1b476b",
    imageLink: "/sdg-images/17.png",
  },
];
